### ISSUE TITLE
error on electron-rebuild

### ISSUE THREAD

**Issue by jsgv** [d3x0r/sack.vfs#3]
Tried to rebuild since, it wasn't working on my Electron app after the `npm install`, and rebuild failed.

```
> electron-rebuild && cd app && npm install && electron-rebuild

✖ Rebuild Failed
An unhandled error occurred inside electron-rebuild
  CXX(target) Release/obj.target/sack_vfs/vfs_module.o
../vfs_module.cc:164:3: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete]
                delete argv;
                ^
                      []
../vfs_module.cc:153:24: note: allocated with 'new[]' here
                Local<Value> *argv = new Local<Value>[2];
                                     ^
../vfs_module.cc:374:4: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete]
                        delete argv;
                        ^
                              []
../vfs_module.cc:366:25: note: allocated with 'new[]' here
                        Local<Value> *argv = new Local<Value>[argc];
                                             ^
2 warnings generated.
  CXX(target) Release/obj.target/sack_vfs/src/sack.o
../src/sack.cc:10428:67: warning: taking address of packed member 'dwSize' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
   new_disk = (struct disk*)OpenSpaceExx( NULL, vol->volname, 0, &vol->dwSize, &created );
                                                                  ^~~~~~~~~~~
../src/sack.cc:10472:66: warning: taking address of packed member 'dwSize' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
  new_disk = (struct disk*)OpenSpaceExx( NULL, vol->volname, 0, &vol->dwSize, &created );
                                                                 ^~~~~~~~~~~
../src/sack.cc:10742:18: warning: taking address of packed member 'files' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
  DeleteListEx( &vol->files DBG_SRC );
                 ^~~~~~~~~~
../src/sack.cc:10746:25: warning: taking address of packed member 'entropy' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
   SRG_DestroyEntropy( &vol->entropy );
                        ^~~~~~~~~~~~
../src/sack.cc:10785:27: warning: taking address of packed member 'lock' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
  while( LockedExchange( &vol->lock, 1 ) ) Relinquish();
                          ^~~~~~~~~
../src/sack.cc:10805:27: warning: taking address of packed member 'lock' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
  while( LockedExchange( &vol->lock, 1 ) ) Relinquish();
                          ^~~~~~~~~
../src/sack.cc:10829:27: warning: taking address of packed member 'lock' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
  while( LockedExchange( &vol->lock, 1 ) ) Relinquish();
                          ^~~~~~~~~
../src/sack.cc:10977:27: warning: taking address of packed member 'lock' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
  while( LockedExchange( &vol->lock, 1 ) ) Relinquish();
                          ^~~~~~~~~
../src/sack.cc:10993:13: warning: taking address of packed member 'files' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
  AddLink( &vol->files, file );
            ^~~~~~~~~~
../src/sack.cc:1860:43: note: expanded from macro 'AddLink'
 #define AddLink(p,v)       ( AddLinkEx( (p),((POINTER)(v)) DBG_SRC ) )
                                          ^
../src/sack.cc:11001:27: warning: taking address of packed member 'lock' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
  while( LockedExchange( &vol->lock, 1 ) ) Relinquish();
                          ^~~~~~~~~
../src/sack.cc:11220:27: warning: taking address of packed member 'lock' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
  while( LockedExchange( &vol->lock, 1 ) ) Relinquish();
                          ^~~~~~~~~
../src/sack.cc:11310:28: warning: taking address of packed member 'lock' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
   while( LockedExchange( &vol->lock, 1 ) ) Relinquish();
                           ^~~~~~~~~
../src/sack.cc:30822:2: warning: all paths through this function will call itself [-Winfinite-recursion]
 {
 ^
../src/sack.cc:33226:27: warning: taking address of packed member 'next' of class or structure 'sack::memory::heap_chunk_tag' may result in an unaligned pointer value [-Waddress-of-packed-member]
        pNew->next->me = &pNew->next;
                          ^~~~~~~~~~
../src/sack.cc:33384:5: warning: taking address of packed member 'next' of class or structure 'sack::memory::heap_chunk_tag' may result in an unaligned pointer value [-Waddress-of-packed-member]
    LinkThing( *prior, next );
    ^~~~~~~~~~~~~~~~~~~~~~~~~
../src/sack.cc:1372:95: note: expanded from macro 'LinkThing'
 #define LinkThing( root, node )       ((( (node)->next = (root) )?         (((root)->me) = &((node)->next)):0),   (((node)->me) = &(root)),              ((root) = (node)) )
                                                                                              ^~~~~~~~~~~~
../src/sack.cc:33385:5: warning: taking address of packed member 'next' of class or structure 'sack::memory::heap_chunk_tag' may result in an unaligned pointer value [-Waddress-of-packed-member]
    LinkThing( next->next, temp );
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/sack.cc:1372:95: note: expanded from macro 'LinkThing'
 #define LinkThing( root, node )       ((( (node)->next = (root) )?         (((root)->me) = &((node)->next)):0),   (((node)->me) = &(root)),              ((root) = (node)) )
                                                                                              ^~~~~~~~~~~~
../src/sack.cc:33385:16: warning: taking address of packed member 'next' of class or structure 'sack::memory::heap_chunk_tag' may result in an unaligned pointer value [-Waddress-of-packed-member]
    LinkThing( next->next, temp );
               ^~~~~~~~~~
../src/sack.cc:1372:134: note: expanded from macro 'LinkThing'
 #define LinkThing( root, node )       ((( (node)->next = (root) )?         (((root)->me) = &((node)->next)):0),   (((node)->me) = &(root)),              ((root) = (node)) )
                                                                                                                                     ^~~~
../src/sack.cc:33386:14: warning: taking address of packed member 'next' of class or structure 'sack::memory::heap_chunk_tag' may result in an unaligned pointer value [-Waddress-of-packed-member]
    prior = &next->next;
             ^~~~~~~~~~
../src/sack.cc:33392:14: warning: taking address of packed member 'next' of class or structure 'sack::memory::heap_chunk_tag' may result in an unaligned pointer value [-Waddress-of-packed-member]
    prior = &temp->next;
             ^~~~~~~~~~
../src/sack.cc:33688:27: warning: taking address of packed member 'next' of class or structure 'sack::memory::heap_chunk_tag' may result in an unaligned pointer value [-Waddress-of-packed-member]
          pc->next->me = &pc->next;
                          ^~~~~~~~
../src/sack.cc:33726:8: warning: taking address of packed member 'next' of class or structure 'sack::memory::heap_chunk_tag' may result in an unaligned pointer value [-Waddress-of-packed-member]
       LinkThing( pc->pRoot->pFirstFree, pc );
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/sack.cc:1372:95: note: expanded from macro 'LinkThing'
 #define LinkThing( root, node )       ((( (node)->next = (root) )?         (((root)->me) = &((node)->next)):0),   (((node)->me) = &(root)),              ((root) = (node)) )
                                                                                              ^~~~~~~~~~~~
../src/sack.cc:57877:11: fatal error: 'openssl/ssl.h' file not found
 #include <openssl/ssl.h>
          ^
21 warnings and 1 error generated.
make: *** [Release/obj.target/sack_vfs/src/sack.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Volumes/MacintoshHD/myapp/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/Users/jesus/.nvm/versions/node/v6.9.1/bin/node" "/Volumes/MacintoshHD/myapp/node_modules/.bin/node-gyp" "rebuild" "--target=1.6.8" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /Volumes/MacintoshHD/myapp/node_modules/sack.vfs
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok

Failed with exit code: 1

Error:   CXX(target) Release/obj.target/sack_vfs/vfs_module.o
../vfs_module.cc:164:3: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete]
                delete argv;
                ^
                      []
../vfs_module.cc:153:24: note: allocated with 'new[]' here
                Local<Value> *argv = new Local<Value>[2];
                                     ^
../vfs_module.cc:374:4: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete]
                        delete argv;
                        ^
                              []
../vfs_module.cc:366:25: note: allocated with 'new[]' here
                        Local<Value> *argv = new Local<Value>[argc];
                                             ^
2 warnings generated.
  CXX(target) Release/obj.target/sack_vfs/src/sack.o
../src/sack.cc:10428:67: warning: taking address of packed member 'dwSize' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
   new_disk = (struct disk*)OpenSpaceExx( NULL, vol->volname, 0, &vol->dwSize, &created );
                                                                  ^~~~~~~~~~~
../src/sack.cc:10472:66: warning: taking address of packed member 'dwSize' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
  new_disk = (struct disk*)OpenSpaceExx( NULL, vol->volname, 0, &vol->dwSize, &created );
                                                                 ^~~~~~~~~~~
../src/sack.cc:10742:18: warning: taking address of packed member 'files' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
  DeleteListEx( &vol->files DBG_SRC );
                 ^~~~~~~~~~
../src/sack.cc:10746:25: warning: taking address of packed member 'entropy' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
   SRG_DestroyEntropy( &vol->entropy );
                        ^~~~~~~~~~~~
../src/sack.cc:10785:27: warning: taking address of packed member 'lock' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
  while( LockedExchange( &vol->lock, 1 ) ) Relinquish();
                          ^~~~~~~~~
../src/sack.cc:10805:27: warning: taking address of packed member 'lock' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
  while( LockedExchange( &vol->lock, 1 ) ) Relinquish();
                          ^~~~~~~~~
../src/sack.cc:10829:27: warning: taking address of packed member 'lock' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
  while( LockedExchange( &vol->lock, 1 ) ) Relinquish();
                          ^~~~~~~~~
../src/sack.cc:10977:27: warning: taking address of packed member 'lock' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
  while( LockedExchange( &vol->lock, 1 ) ) Relinquish();
                          ^~~~~~~~~
../src/sack.cc:10993:13: warning: taking address of packed member 'files' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
  AddLink( &vol->files, file );
            ^~~~~~~~~~
../src/sack.cc:1860:43: note: expanded from macro 'AddLink'
 #define AddLink(p,v)       ( AddLinkEx( (p),((POINTER)(v)) DBG_SRC ) )
                                          ^
../src/sack.cc:11001:27: warning: taking address of packed member 'lock' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
  while( LockedExchange( &vol->lock, 1 ) ) Relinquish();
                          ^~~~~~~~~
../src/sack.cc:11220:27: warning: taking address of packed member 'lock' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
  while( LockedExchange( &vol->lock, 1 ) ) Relinquish();
                          ^~~~~~~~~
../src/sack.cc:11310:28: warning: taking address of packed member 'lock' of class or structure 'sack::SACK_VFS::volume' may result in an unaligned pointer value [-Waddress-of-packed-member]
   while( LockedExchange( &vol->lock, 1 ) ) Relinquish();
                           ^~~~~~~~~
../src/sack.cc:30822:2: warning: all paths through this function will call itself [-Winfinite-recursion]
 {
 ^
../src/sack.cc:33226:27: warning: taking address of packed member 'next' of class or structure 'sack::memory::heap_chunk_tag' may result in an unaligned pointer value [-Waddress-of-packed-member]
        pNew->next->me = &pNew->next;
                          ^~~~~~~~~~
../src/sack.cc:33384:5: warning: taking address of packed member 'next' of class or structure 'sack::memory::heap_chunk_tag' may result in an unaligned pointer value [-Waddress-of-packed-member]
    LinkThing( *prior, next );
    ^~~~~~~~~~~~~~~~~~~~~~~~~
../src/sack.cc:1372:95: note: expanded from macro 'LinkThing'
 #define LinkThing( root, node )       ((( (node)->next = (root) )?         (((root)->me) = &((node)->next)):0),   (((node)->me) = &(root)),              ((root) = (node)) )
                                                                                              ^~~~~~~~~~~~
../src/sack.cc:33385:5: warning: taking address of packed member 'next' of class or structure 'sack::memory::heap_chunk_tag' may result in an unaligned pointer value [-Waddress-of-packed-member]
    LinkThing( next->next, temp );
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/sack.cc:1372:95: note: expanded from macro 'LinkThing'
 #define LinkThing( root, node )       ((( (node)->next = (root) )?         (((root)->me) = &((node)->next)):0),   (((node)->me) = &(root)),              ((root) = (node)) )
                                                                                              ^~~~~~~~~~~~
../src/sack.cc:33385:16: warning: taking address of packed member 'next' of class or structure 'sack::memory::heap_chunk_tag' may result in an unaligned pointer value [-Waddress-of-packed-member]
    LinkThing( next->next, temp );
               ^~~~~~~~~~
../src/sack.cc:1372:134: note: expanded from macro 'LinkThing'
 #define LinkThing( root, node )       ((( (node)->next = (root) )?         (((root)->me) = &((node)->next)):0),   (((node)->me) = &(root)),              ((root) = (node)) )
                                                                                                                                     ^~~~
../src/sack.cc:33386:14: warning: taking address of packed member 'next' of class or structure 'sack::memory::heap_chunk_tag' may result in an unaligned pointer value [-Waddress-of-packed-member]
    prior = &next->next;
             ^~~~~~~~~~
../src/sack.cc:33392:14: warning: taking address of packed member 'next' of class or structure 'sack::memory::heap_chunk_tag' may result in an unaligned pointer value [-Waddress-of-packed-member]
    prior = &temp->next;
             ^~~~~~~~~~
../src/sack.cc:33688:27: warning: taking address of packed member 'next' of class or structure 'sack::memory::heap_chunk_tag' may result in an unaligned pointer value [-Waddress-of-packed-member]
          pc->next->me = &pc->next;
                          ^~~~~~~~
../src/sack.cc:33726:8: warning: taking address of packed member 'next' of class or structure 'sack::memory::heap_chunk_tag' may result in an unaligned pointer value [-Waddress-of-packed-member]
       LinkThing( pc->pRoot->pFirstFree, pc );
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/sack.cc:1372:95: note: expanded from macro 'LinkThing'
 #define LinkThing( root, node )       ((( (node)->next = (root) )?         (((root)->me) = &((node)->next)):0),   (((node)->me) = &(root)),              ((root) = (node)) )
                                                                                              ^~~~~~~~~~~~
../src/sack.cc:57877:11: fatal error: 'openssl/ssl.h' file not found
 #include <openssl/ssl.h>
          ^
21 warnings and 1 error generated.
make: *** [Release/obj.target/sack_vfs/src/sack.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Volumes/MacintoshHD/myapp/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/Users/jesus/.nvm/versions/node/v6.9.1/bin/node" "/Volumes/MacintoshHD/myapp/node_modules/.bin/node-gyp" "rebuild" "--target=1.6.8" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /Volumes/MacintoshHD/myapp/node_modules/sack.vfs
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (/Volumes/MacintoshHD/myapp/node_modules/spawn-rx/lib/src/index.js:262:84)
    at SafeSubscriber.__tryOrUnsub (/Volumes/MacintoshHD/myapp/node_modules/rxjs/Subscriber.js:238:16)
    at SafeSubscriber.error (/Volumes/MacintoshHD/myapp/node_modules/rxjs/Subscriber.js:197:26)
    at Subscriber._error (/Volumes/MacintoshHD/myapp/node_modules/rxjs/Subscriber.js:128:26)
    at Subscriber.error (/Volumes/MacintoshHD/myapp/node_modules/rxjs/Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (/Volumes/MacintoshHD/myapp/node_modules/rxjs/Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (/Volumes/MacintoshHD/myapp/node_modules/rxjs/Subscriber.js:102:18)
    at SafeSubscriber._next (/Volumes/MacintoshHD/myapp/node_modules/spawn-rx/lib/src/index.js:236:65)
    at SafeSubscriber.__tryOrUnsub (/Volumes/MacintoshHD/myapp/node_modules/rxjs/Subscriber.js:238:16)
    at SafeSubscriber.next (/Volumes/MacintoshHD/myapp/node_modules/rxjs/Subscriber.js:185:22)
```

**Comment by d3x0r** [comment]
amongst all the warnings (which I'll work in cleaning) 

../src/sack.cc:57877:11: fatal error: 'openssl/ssl.h' file not found

Something is wrong with your node headers you're building against.

**Comment by d3x0r** [comment]
Okay maybe that is something I can work around, added some conditions to try and get ssl headers appropriately as specified here
https://github.com/nodejs/node-gyp/wiki/Linking-to-OpenSSL 

commited and published new version.

**Comment by d3x0r** [comment]
did that fix it or is it no change?

**Comment by d3x0r** [comment]
I'm going to close this assuming it's fixed; would still appreciate a second opinion.  I don't have a mac, and Mark Nadal's system had no issues; apparently Node was installed differently?
